/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GrokImport } from './routes/grok'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const GrokRoute = GrokImport.update({
  id: '/grok',
  path: '/grok',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/grok': {
      id: '/grok'
      path: '/grok'
      fullPath: '/grok'
      preLoaderRoute: typeof GrokImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grok': typeof GrokRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grok': typeof GrokRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/grok': typeof GrokRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grok'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grok'
  id: '__root__' | '/' | '/grok'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrokRoute: typeof GrokRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrokRoute: GrokRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/grok"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/grok": {
      "filePath": "grok.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
